import { GetStaticProps } from "next";
import "./global.css";
import { ApolloWrapper } from "./lib/apollo-wrapper";
import NavBar from "./navbar";
import Title from "./title";
import { gql, useQuery } from "@apollo/client";
import { GET_USER_BY_ID } from "./api/graphql/queries/userQueries";

export const metadata = {
  title: "Game Club",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body>
          <main className="content">
            <div className="buffer"></div>
            <Title/>
            <div className="buffer"></div>
            <NavBar/>
            <div className="buffer"></div>

            <ApolloWrapper>
            {children}
            </ApolloWrapper>
          </main>
      </body>
    </html>
  );
}
