import "./global.css";
import NavBar from "./navbar";
import Title from "./title";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
          <main className="content">
            <div className="buffer"></div>
            <Title/>
            <div className="buffer"></div>
            <NavBar/>
            <div className="buffer"></div>

            {children}
          </main>
      </body>
    </html>
  );
}
