import "./global.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <ul>
              <li>
                <a href="/lfg">LFG</a>
              </li>
              <li>
                <a href="/reviews">Reviews</a>
              </li>
              <li>
                <a href="/forum">Forum</a>
              </li>
            </ul>
          </nav>
          {children}
        </main>
      </body>

    </html>
  )
}
