import "./global.css";
import NavBar from "./navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="content">
          <main>
            <div className="buffer"></div>
            <NavBar/>

            <div>{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
